version: 2.1

jobs:
  unit:
    environment:
      DBT_INVOCATION_ENV: circle
    docker:
      - image: fishtownanalytics/test-container:9
    steps:
      - checkout

  integration:
    environment:
      DBT_INVOCATION_ENV: circle
      DBT_MYSQL_SERVER_NAME: mysql
    docker:
      - image: fishtownanalytics/test-container:9
      - image: mysql:8.0
        environment:
          MYSQL_ROOT_PASSWORD: dbt
        name: mysql
    steps:
      - checkout

workflows:
  version: 2
  test-everything:
    jobs:
      - unit
      - integration:
          requires:
            - unit
